### ISSUE TITLE
source.json should be a source.yaml, just for consistency

### ISSUE THREAD

**Issue by christoph-jerolimov** [redhat-developer/rhdh-plugin-export-utils#19]
PRs like this:

* https://github.com/redhat-developer/rhdh-plugin-export-overlays/pull/948

creates a `source.json` (manually formatted for readability) like this:

```json
{
  "repo": "https://github.com/backstage/community-plugins",
  "repo-ref": "335037a9f57eef5a989363cb9779cfaeb8c81f9b",
  "repo-flat": false
}
```

Since everything in the Backstage world is using YAMLs, and also the PR creates a `plugins-list.yaml` I would recommend to create a `source.yaml` as well

```yaml
repo: "https://github.com/backstage/community-plugins"
repo-ref: "335037a9f57eef5a989363cb9779cfaeb8c81f9b"
repo-flat: false
```
